import java.util.regex.Pattern

enum class Lexem(pattern: String) {
    NUM("0|[1-9]{1}[0-9]*"),

    WHITESPACE("\\s+"),

    BINARY("0b[0-1]+\\b"),
    FLOAT("[+-]?([0-9]+)([.][0-9]+)?f\\b"),
    DOUBLE("[+-]?([0-9]+[.])[0-9]+\\b"),
    LONG("[+-]?[0-9]+L\\b"),
    INTEGRAL("[+-]?[0-9]+\\b"),

    LCB("\\{"),
    RCB("\\}"),
    LB("\\("),
    RB("\\)"),
    C_OP(";"),
    GOTO(""),
    GOTO_INDEX(""),
    ASSIGN_OP("="),
    METHOD("\\."),
    FUNC_OP("add|remove|get|contains"),
    TYPE_W("new"),
    TYPE("Set|List"),
    WHILE("while"),
    FOR("for"),
    IF("if"),
    ELSE("else"),
    PRINT("print"),
    BOOL_OP("<|>|<=|>=|==|!="),
    BOOL("true|false"),
    VAR("[a-zA-Z][a-zA-Z0-9_]*"),
    INC("\\+\\+"),
    DEC("\\--"),
    OP("[*|/|+|-]"),

    BLOCKCOMMENT("/\\*([^*]|[\\r\\n]|(\\*+([^*/]|[\\r\\n])))*\\*+/"),
    SINGLELINECOMMENT("//.*+"),


    TYPEALIAS("typealias\\b"),
    INTERFACE("interface\\b"),
    CONTINUE("continue\\b"),
    PACKAGE("package\\b"),
    IMPORT("import\\b"),
    RETURN("return\\b"),
    OBJECT("object\\b"),
    BREAK("break\\b"),
    CLASS("class\\b"),
    THROW("throw\\b"),
    FALSE("false\\b"),
    SUPER("super\\b"),
    TYPEOF("typeof\\b"),
    WHEN("when\\b"),
    TRUE("true\\b"),
    THIS("this\\b"),
    NULL("null\\b"),
    TRY("try\\b"),
    VAL("val\\b"),
    FUN("fun\\b"),
    IS("is\\b"),
    IN("in\\b"),
    DO("do\\b"),
    AS("as\\b"),

    RESERVED("\\.\\.\\."),
    EQEQEQ("==="),
    EXCLEQEQ("!=="),
    NOTIN("!in\\s+"),
    NOTIS("!is\\s+"),
    ASSAFE("as\\?"),
    INCR("\\+\\+"),
    DECR("--"),
    LTEQ("<="),
    GTEQ(">="),
    DOUBLEEQ("=="),
    EXCLEQ("!="),
    ANDAND("&&"),
    OROR("\\|\\|"),
    MULTEQ("//*="),
    DIVEQ("/="),
    PEREQ("%/"),
    PLUSEQ("//+="),
    MINUSEQ("-="),
    ARROW("->"),
    DOUBLEARROW("=>"),
    RANGE("\\.\\."),
    COLONCOLON("::"),
    LBRACKET("\\["),
    RBRACKET("\\]"),
    LBRACE("\\{"),
    RBRACE("\\}"),
    LPAR("\\("),
    RPAR("\\)"),
    DOT("\\."),
    MUL("\\*"),
    PLUS("\\+"),
    MINUS("-"),
    EXCL("!"),
    DIV("/"),
    PERC("%"),
    LT("<"),
    GT(">"),
    QUEST("\\?"),
    COLON(":"),
    SEMICOLON(";"),
    EQ("="),
    COMMA(","),
    HASH("#"),
    AT("@"),
    IGNORED("\\b_\\b"),

    CHAR("'.{1}'"),
    STR("(?s)\".*?\""),

    ID("[a-zA-Z][a-zA-Z0-9_]*"),

    ERROR(".+");

    val pattern: Pattern = Pattern.compile(pattern)

}